theme = "catppuccin_macchiato"

[editor]
auto-info = false
line-number = "relative"
gutters = ["spacer", "diagnostics", "spacer", "diff", "line-numbers", "spacer"]
color-modes = true
cursorline = true
idle-timeout = 50
completion-trigger-len = 1

[editor.inline-diagnostics]
cursor-line = "error" 
other-lines = "disable"

[editor.search]
smart-case = false

[editor.statusline]
left = ["mode", "spacer", "version-control", "workspace-diagnostics"]
center = ["file-name", "file-modification-indicator", "file-type"]
right = ["diagnostics", "selections", "primary-selection-length", "position"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
"space" = { q = ":q", w = ":w", c = ":buffer-close", o = ":buffer-close-others", f = "file_picker_in_current_directory", l = ":reload-all" }
"'" = "repeat_last_motion"
L = "extend_to_line_end"
H = "extend_to_line_start"
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

[keys.select]
"space" = { q = ":q", w = ":w", c = ":buffer-close", o = ":buffer-close-others", f = "file_picker_in_current_directory", l = ":reload-all" }
"'" = "repeat_last_motion"
L = "extend_to_line_end"
H = "extend_to_line_start"
"A-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"A-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
