[[language]]
name = "go"
language-servers = ["gopls"]
formatter = { command = "goimports" }
roots = ["go.mod"]
diagnostic-severity = "hint"
auto-format = true

[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt" }

[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
file-types = ["ts"]
auto-format = true

[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
file-types = ["js"]
auto-format = true

[[language]]
name = "svelte"
language-servers = ["svelteserver"]
roots = ["svelte.config.js"]
auto-format = true

[[language]]
name = "tsx"
language-servers = ["typescript-language-server"]
auto-format = true

